#define GREY(g) g g g
#define BLACK                       GREY(0)
#define WHITE                       GREY(1)

#define RED                         1 0 0
#define GREEN                       0 1 0
#define BLUE                        0 0 1
#define CYAN                        0 1 1
#define YELLOW                      1 1 0
#define MAGENTA                     1 0 1

#define PINK                        1 0.8 0.8
#define MINT                        0.8 1 0.8
#define LTBLUE                      0.5 0.5 1
#define LTYELLOW                    1 1 0.5
#define ORANGE                      1 0.5 0
#define BROWN			    #8C 62 38
